services:

  backend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev.api
    restart: unless-stopped
    env_file:
      - ../config/.env.dev
      - ../.env.local
      - ../.env
    ports:
      - '${SERVER_PORT:-3000}:${SERVER_PORT:-3000}'
      - "5005:5005"  # Debug port
    volumes:
      # Volume mount for hot reload - critical for development
      - ./apps/api/src:/app/src
      - ./apps/api/pom.xml:/app/pom.xml
      - ./apps/api/target:/app/target
      # Maven cache to avoid re-downloading dependencies
      - maven-cache-dev:/root/.m2
    depends_on:
      db:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3



  db:
    image: postgres:latest
  
    env_file:
    - ../config/.env.dev
    - ../.env.local
    - ../.env

    ports:
    - '${DB_PORT:-5432}:${DB_PORT:-5432}'


    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb "] # ? make variables dynamic
      interval: 5s
      retries: 10
      timeout: 5s

    volumes:
      - db_data_dev:/var/lib/postgresql/data

volumes:
  postgres-data:
