
@baseUrl = http://localhost:8080/api



############################
### Register a new user
# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "tokenId": "sqd645qds4685sdf"
}











############################
# @name test-connection
GET {{baseUrl}}/health
Content-Type: application/json
